// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg-mKHIQilDTS9xNV8M6xcsxGnF7eij0s',
    appId: '1:374704705020:web:e94a33b81628c6c9203679',
    messagingSenderId: '374704705020',
    projectId: 'financial-85944',
    authDomain: 'financial-85944.firebaseapp.com',
    storageBucket: 'financial-85944.firebasestorage.app',
    measurementId: 'G-B0BJF8SXES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6P39CQ4J1Am-cHfEtzv8Rt3xj-qhisBs',
    appId: '1:374704705020:android:29f6f690b6b06c96203679',
    messagingSenderId: '374704705020',
    projectId: 'financial-85944',
    storageBucket: 'financial-85944.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3S2cCA0g6v_NWgzoKx46O5cEPA5JwlY',
    appId: '1:374704705020:ios:0d1d64b9fe14e6e2203679',
    messagingSenderId: '374704705020',
    projectId: 'financial-85944',
    storageBucket: 'financial-85944.firebasestorage.app',
    iosBundleId: 'com.example.financial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3S2cCA0g6v_NWgzoKx46O5cEPA5JwlY',
    appId: '1:374704705020:ios:0d1d64b9fe14e6e2203679',
    messagingSenderId: '374704705020',
    projectId: 'financial-85944',
    storageBucket: 'financial-85944.firebasestorage.app',
    iosBundleId: 'com.example.financial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg-mKHIQilDTS9xNV8M6xcsxGnF7eij0s',
    appId: '1:374704705020:web:5428d2562d18afb5203679',
    messagingSenderId: '374704705020',
    projectId: 'financial-85944',
    authDomain: 'financial-85944.firebaseapp.com',
    storageBucket: 'financial-85944.firebasestorage.app',
    measurementId: 'G-TB9N2J5RD3',
  );
}
